name: Git Automation

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set Git Config
      run: |
        git config user.name "KhanAnupamShafi"
        git config user.email "deep71.bd@gmail.com"

    - name: Make Changes
      run: |
        echo "<?php // Added on $(date '+%Y-%m-%d %H:%M:%S')"
        echo "echo date('Y-m-d H:i:s'); ?>" >> cron-task.php


    - name: Commit and Push Changes
      run: |
        git add .
        git commit -m "$(date '+%Y-%m-%d %H:%M:%S') - Auto Action "
        git push


# name: Daily Commit

# on:
#   push:
#     branches:
#       - main

# jobs:
#   commit:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout repository
#       uses: actions/checkout@v2

#     - name: Set Git Config
#       run: |
#         git config user.name "KhanAnupamShafi"
#         git config user.email "deep71.bd@gmail.com"

#     - name: Make Changes
#       run: echo "$(date)" > daily-commit.txt

#     - name: Commit and Push Changes
#       uses: ad-m/github-push-action@master
#       with:
#         github_token: ${{ secrets.GITHUB_TOKEN }}
#         branch: main
